content:
  - name: docs
    label: Documentation
    path: assets
    type: collection
    view: 
      fields: [ title, order ]
      primary: title
    fields: 
      - { name: test, label: title, type: string }
