media: assets/images
content:
  - name: home
    label: Home Page
    type: file
    path: index.html
    fields:
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text}
